# email: ntsagkopoulos@sagarobotics.com

version: '3'
services:
    gripper_perception:
        image: saga/rasberry_perception:detectron2_jetson
        container_name: detectron2_backend
        network_mode: host
        environment:
            - ROS_MASTER_URI=${ROS_MASTER_URI}
            - ROS_IP=${ROS_IP}
            - SERVICE_NAME=gripper_perception
        runtime: nvidia
        privileged: true
        entrypoint: /bin/bash ./entrypoint.sh
        volumes:
        - ./model_final.pth:/model.pth
        - ./mask_rcnn_R_50_FPN_3x.yaml:/config.yaml
        - ./start_backend.sh:/start_backend.sh